"use client";
import { Inter } from "next/font/google";
import Link from "next/link";
import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({ children }) {
   const pathname = usePathname();

   return (
      <html lang="en">
         <body className={inter.className}>
            <nav>
               {pathname === "/" ? (
                  <>
                     <Link href="/login">Login</Link>
                     <Link href="/about">About</Link>
                     <Link href="/blog">Blog</Link>
                  </>
               ) : (
                  <Link href="/">Home </Link>
               )}
            </nav>
            {children}
         </body>
      </html>
   );
}
